"""Check local setup without printing values or contacting a wallet or model."""

import argparse
import os
import shlex
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from restock.config import RestockError, Settings  # noqa: E402

REQUIRED = ("OPENAI_API_KEY", "LANGSMITH_API_KEY", "LANGSMITH_WORKSPACE_ID")
NAMES = {
    *REQUIRED,
    "OPENAI_MODEL",
    "RESTOCK_MODE",
    "RESTOCK_MAX_BUDGET_CENTS",
    "RESTOCK_APPROVAL_WAIT_SECONDS",
    "RESTOCK_PUBLIC_URL",
    "RESTOCK_UPDATES_SIGNING_KEY",
}


def settings_from_file(path: Path, environment=None, *, names=NAMES) -> dict:
    """Read the simple KEY=value format generated by setup; never echo its contents."""
    values = {}
    if path.is_file():
        for line in path.read_text().splitlines():
            line = line.strip().removeprefix("export ")
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, raw = line.split("=", 1)
            key = key.strip()
            if key not in names:
                continue
            try:
                parsed = shlex.split(raw, comments=True)
                if len(parsed) > 1:
                    raise ValueError()
            except ValueError:
                raise ValueError(f"Check quoting for {key}; no value was printed") from None
            values[key] = parsed[0] if parsed else ""
    values.update(
        {
            k: v
            for k, v in (os.environ if environment is None else environment).items()
            if k in names
        }
    )
    return values


def problems(values: dict, require_rehearsal=False) -> list[str]:
    issues = []
    if values.get("RESTOCK_PUBLIC_URL") or values.get("RESTOCK_UPDATES_SIGNING_KEY"):
        from restock.notifications import configuration

        try:
            configuration(values)
        except RestockError:
            issues.append("Run scripts/configure_updates.py with the HTTPS deployment URL.")
    for key in REQUIRED:
        value = values.get(key, "").strip()
        if not value or value.startswith(("<", "${", "your_", "your-")):
            issues.append(f"Set {key} privately in the app's .env or your shell.")
    try:
        settings = Settings.load(values)
        if require_rehearsal and settings.mode != "rehearsal":
            issues.append("Set RESTOCK_MODE=rehearsal for this first test.")
    except RestockError:
        issues.append("Fix RESTOCK_MODE, budget, or approval-wait settings; see .env.example.")
    return issues


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, default=ROOT / ".local/app")
    parser.add_argument(
        "--rehearsal", action="store_true", help="Require rehearsal for the first test"
    )
    args = parser.parse_args()
    issues = []
    if not (args.project / "agent.py").is_file():
        issues.append("Run scripts/setup.py to prepare the app first.")
    try:
        values = settings_from_file(args.project / ".env")
        issues.extend(problems(values, args.rehearsal))
    except ValueError as error:
        values = {}
        issues.append(str(error))
    for program in ("uv", "sfw"):
        if not shutil.which(program):
            issues.append(f"Install {program} before launching MDA.")
    for issue in issues:
        print("NEEDS SETUP: " + issue)
    if issues:
        return 2
    print("PASS: required local settings are present; no values were printed.")
    print(
        "This does not verify key validity, model access, hosted identity, or sandbox provisioning."
    )
    print("Next: sfw uv run mda dev .local/app")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
